from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    DATABASE_URL: str
    SECRET_KEY: str
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 60

    RESEND_API_KEY: str = ""
    RESEND_FROM: str = "FizMat Social <noreply@fizmat.kz>"

    SMTP_HOST: str = ""
    SMTP_PORT: int = 587
    SMTP_SSL: bool = False   # True for port 465 (SSL), False for port 587 (STARTTLS)
    SMTP_USER: str = ""
    SMTP_PASSWORD: str = ""
    SMTP_FROM: str = ""

    SUPABASE_URL: str = ""
    SUPABASE_SERVICE_KEY: str = ""

    VAPID_PRIVATE_KEY: str = ""   # base64-encoded PEM, generated by generate_vapid_keys.py
    VAPID_PUBLIC_KEY: str = ""    # base64url uncompressed EC point, for browser applicationServerKey
    VAPID_CLAIM_EMAIL: str = "mailto:admin@fizmat.kz"

    # Set to your actual frontend domain in production, e.g. "https://fizmat.example.com"
    ALLOWED_ORIGINS: str = "*"

    class Config:
        env_file = ".env"


settings = Settings()
